server:
  port: 8193
turbine:
  app-config: consumer-demo
  aggregator:
    clusterConfig: prontera
  cluster-name-expression: metadata['cluster']
eureka:
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: hystrix-dashboard
  cloud:
    loadbalancer:
      retry:
        enabled: true