server:
  port: ${PORT:7020}
eureka:
    instance:
        leaseExpirationDurationInSeconds: ${leaseExpirationDurationInSeconds:2}
        leaseRenewalIntervalInSeconds: ${leaseRenewalIntervalInSeconds:1}
        preferIpAddress: ${preferIpAddress:true}
    client:
        registerWithEureka: ${registerWithEureka:true}
        fetchRegistry: ${fetchRegistry:true}
        registryFetchIntervalSeconds: ${registryFetchIntervalSeconds:3}
        serviceUrl:
            defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/)}
management:
    security:
        enabled: false
info:
    version: @project.version@
spring:
  application:
    name: ${SERVICE_NAME:spring-boot-admin}
  cloud:
    loadbalancer:
      retry:
        enabled: true
