server:
  port: 7291
eureka:
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: zuul-server
  cloud:
    loadbalancer:
      retry:
        enabled: true